lib/phxcrd_web/admin_router.ex
defmodule PhxcrdWeb.AdminRouter do
  use PhxcrdWeb, :router

  scope "/admin", PhxcrdWeb do
    resources "/authorities", AuthorityController, except: [:delete]
    resources "/permissions", PermissionController
    resources "/versions", VersionController, only: [:index, :show]
    resources "/users", UserController, except: [:delete]
    get "/users/:id/change-password", UserController, :change_password_get
    put "/users/:id/change-password", UserController, :change_password_post

    live "/authorities_live", AuthorityLive.Index, :index
    live "/authorities_live/new", AuthorityLive.Index, :new
    live "/authorities_live/:id/edit", AuthorityLive.Index, :edit
    live "/authorities_live/:id/delete", AuthorityLive.Index, :delete
    live "/authorities_live/:id", AuthorityLive.Show, :show
    live "/authorities_live/:id/show/edit", AuthorityLive.Show, :edit

    get "/users/:id/photo", UserController, :get_photo
  end
end

lib/phxcrd_web/router.ex
defmodule PhxcrdWeb.Router do
  use PhxcrdWeb, :router
  use Plug.ErrorHandler
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # plug :fetch_flash
    # plug Phoenix.LiveView.Flash
    plug :fetch_live_flash
    plug :put_root_layout, {PhxcrdWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phxcrd.Plugs.SetCurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Phxcrd.Plugs.SetCurrentUser
  end

  scope "/", PhxcrdWeb do
    pipe_through :browser

    # forward "/admin", AdminRouter
    match :*, "/admin/*path", AdminRouter, :any

    resources "/sessions", SessionController,
      only: [:new, :create, :delete],
      singleton: true

    get "/", PageController, :index
    get "/test-sentry", PageController, :test_sentry
    get "/test-mail", PageController, :test_mail
    get "/test-pdf", PageController, :test_pdf
    get "/test-xlsx", PageController, :test_xlsx
    get "/test-presence", PageController, :test_presence
    get "/test-live", PageController, :test_live

    live "/test-mutex", MutexLive, :index
  end

  scope "/api", PhxcrdWeb do
    pipe_through :api

    get "/search_authorities", ApiController, :search_authorities
  end

  if Mix.env() == :dev do
    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PhxcrdWeb.Telemetry
    end
  end
end

lib/phxcrd_web/controllers/user_controller.ex
defmodule PhxcrdWeb.UserController do
  use PhxcrdWeb, :controller
  alias Phxcrd.Auth
  alias Phxcrd.Auth.{User, Authority, Permission, UserPermission}
  alias Phxcrd.Plugs
  alias Phxcrd.Repo
  alias PhxcrdWeb.QueryFilterEx
  import Canada, only: [can?: 2]
  import Ecto.Query, only: [from: 2]

  plug Plugs.UserSignedIn
  plug :cancan

  defp cancan(conn, _options) do
    if %User{permissions: conn.assigns[:perms]} |> can?(index(User)) do
      conn
    else
      conn
      |> put_flash(:error, "Access Denied!")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt
    end
  end

  @user_filters [
    %{name: :username, type: :string, binding: :user, field_name: :username, method: :ilike},
    %{
      name: :authority_name,
      type: :string,
      binding: :authority,
      field_name: :name,
      method: :icontains
    },
    %{
      name: :permission_name,
      type: :string,
      binding: :permission,
      field_name: :name,
      method: :ilike
    },
    %{name: :last_login_date, type: :date, binding: :user, field_name: :last_login, method: :date}
  ]

  @user_sort_fields [
    "user__username",
    "user__name",
    "user__last_login"
  ]

  def index(conn, params) do
    changeset = QueryFilterEx.get_changeset_from_params(params, @user_filters)

    users =
      from(u in User,
        as: :user,
        left_join: a in Authority,
        as: :authority,
        on: a.id == u.authority_id,
        left_join: up in UserPermission,
        on: up.user_id == u.id,
        left_join: p in Permission,
        as: :permission,
        on: up.permission_id == p.id,
        preload: [authority: a, permissions: p]
      )
      |> QueryFilterEx.filter(changeset, @user_filters)
      |> QueryFilterEx.sort_by_params(params, @user_sort_fields)
      |> Repo.all()
    # import IEx; IEx.pry
    render(conn, :index, users: users, changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    render(conn, :show, user: user)
  end

  def new(conn, _params) do
    changeset = Auth.change_user(%User{})
    render(conn, :new, changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Auth.create_db_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: AdminRoutes.user_path(conn, :show, user))

      {:error, changeset} ->
        render(conn, :new, changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    changeset = Auth.change_user(user)
    render(conn, :edit, user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)

    user_params = Map.merge(%{"authority_id" => nil}, user_params)

    case Auth.update_user_and_perms(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: AdminRoutes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :edit, user: user, changeset: changeset)
    end
  end

  def change_password_get(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    changeset = Auth.change_user(user)
    render(conn, :change_password, user: user, changeset: changeset)
  end

  def change_password_post(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)

    case Auth.update_user_password(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User password updated successfully.")
        |> redirect(to: AdminRoutes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :change_password, user: user, changeset: changeset)
    end
  end

  def get_photo(conn, %{"id" => id}) do
    # Notice that here i could do any checks I want (authorization) for example display
    # the image only to admins and the current user. The most important thing here
    # is that because `send_file` is used to send the file it will be a fast operation
    # and will not introduce any problems to the application.
    # Also notice that the cancan plugin will run for all actions in this controller
    user = Auth.get_user!(id)

    case user.photo_path do
      nil ->
        conn |> redirect(external: "https://picsum.photos/200")

      v ->
        conn
        |> put_resp_content_type("image/jpg")
        |> send_file(200, v)
    end
  end
end

lib/phxcrd_web/controllers/user_html.ex
defmodule PhxcrdWeb.UserHTML do
  use PhxcrdWeb, :html

  embed_templates "user_html/*"
end

lib/phxcrd_web/templates/user/change_password.html.eex
<%= title("Change password") %>

<%= form_for @changeset, AdminRoutes.user_path(@conn, :change_password_post, @user), [class: "pf-c-form pf-m-horizontal"], fn f -> %>

<%= if @changeset.action do %>
<div class="alert alert-danger">
  <p><%= gettext("Problems while saving") %></p>
</div>
<% end %>
<%= get_form_pass_field(f, :password, gettext("Password")) %>
<%= get_form_pass_field(f, :password_confirmation, gettext("Password confirm")) %>

<div>
  <%= submit gettext("Save"), class: "pf-c-button pf-m-primary"  %>
</div>
<% end %>

<span><%= link "Back", to: AdminRoutes.user_path(@conn, :index), class: "pf-c-button pf-m-secondary" %></span>

lib/phxcrd_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, AdminRoutes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: AdminRoutes.user_path(@conn, :index), class: "btn btn-secondary" %></span>

lib/phxcrd_web/templates/user/extra_scripts.html.eex
<%= if action_name(@conn) in [:edit, :new, :create, :update] do %>
<script>
    // Render me on :new and :edit
    $(function () {
        $('#user_permissions').select2();

        $('#user_authority_id').select2({
          //language: "el",
          allowClear: true,
          placeholder: 'Select authority',
          ajax: {
            url: '<%= Routes.api_path(@conn, :search_authorities) %>',
            dataType: 'json',
            delay: 150,
            minimumInputLength: 2
          }
        });
    })
</script>
<% end %>

lib/phxcrd_web/templates/user/form.html.eex
<%= form_for @changeset, @action, [multipart: true, class: "pf-c-form pf-m-horizontal"], fn f -> %>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p><%= gettext("Problems while saving") %></p>
  </div>
<% end %>

<%= get_form_text_field(f, :username, gettext("Username")) %>
<%= get_form_check_field(f, :is_enabled, gettext("Is enabled") ) %>
<%= get_form_text_field(f, :name, gettext("Name")) %>
<%= get_form_text_field(f, :email, gettext("Email")) %>
<%= get_form_text_field(f, :first_name, gettext("First name")) %>
<%= get_form_text_field(f, :last_name, gettext("Last name")) %>

<%= get_form_select_field(f, :authority_id, gettext("Authority"), [
      (with sv when not is_nil(sv) <- get_select_value(@changeset, :authority_id),
                                  a <- Phxcrd.Auth.get_authority!(sv), do: {a.name, a.id})
    ]) %>

<%= get_form_multi_select_field(f, :permissions, gettext("Permissions"), (
  Phxcrd.Auth.list_permissions |> Enum.map(&{&1.name, &1.id})
  ), if(assigns[:user], do: Enum.map(@user.permissions, &(&1.id)), else: [])) %>

Current: <%= @changeset.data.photo_path %>

<div class='column'>
  <div class="form-group">
    <%= label f, :photo %>
    <%= file_input f, :photo, class: "form-control" %>
  </div>
  </div>

<div>
  <%= submit gettext("Save"), class: "btn btn-primary" %>
</div>

<% end %>

lib/phxcrd_web/templates/user/index.html.eex
<%= title(gettext("User list")) %>

<%= form_for @changeset, AdminRoutes.user_path(@conn, :index), [method: :get, class: "row row-cols-md-auto g-3 align-items-center", as: :filter],  fn f -> %>
  <%= get_form_text_field(f, :username, gettext("Username")) %>
  <%= get_form_text_field(f, :authority_name, gettext("Authority name")) %>
  <%= get_form_text_field(f, :permission_name, gettext("Permission name")) %>
  <%= get_form_text_field(f, :last_login_date, gettext("Last login date")) %>

  <div class="col-12 d-flex align-self-end">
    <%= submit gettext("Filter"), class: "btn btn-primary" %>
    <%= link gettext("Reset"), to: AdminRoutes.user_path(@conn, :index), class: "btn btn-secondary" %>
  </div>
</div>

<% end %>

<table class='table table-sm'>
  <thead>
    <tr>
      <th>
        <%= link gettext("Username"), to: create_order_url(@conn, "user__username") %>
      </th>
      <th>
        <%= link gettext("Name"), to: create_order_url(@conn, "user__name") %>
      </th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Am / Am phxcrd</th>
      <th>Kind</th>

      <th>
        <%= link gettext("Last login"), to: create_order_url(@conn, "user__last_login") %>
      </th>
      <th>Is enabled</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.name %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.am %> / <%= user.am_phxcrd %></td>
      <td><%= user.kind %></td>

      <td><%= to_local_time_str user.last_login %></td>
      <td><%= user.is_enabled %></td>

      <td>
        <%= link "Show", class: "btn btn-secondary btn-sm", to: AdminRoutes.user_path(@conn, :show, user) %>
        <%= link "Edit", class: "btn btn-secondary btn-sm", to: AdminRoutes.user_path(@conn, :edit, user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<span><%= link gettext("New User"), to: AdminRoutes.user_path(@conn, :new), class: "btn btn-primary btn-lg" %></span>

lib/phxcrd_web/templates/user/new.html.eex
<%= title gettext "New User" %>

<%= render "form.html", Map.put(assigns, :action, AdminRoutes.user_path(@conn, :create)) %>

<span><%= link "Back", to: AdminRoutes.user_path(@conn, :index), class: "btn btn-secondary" %></span>

lib/phxcrd_web/templates/user/show.html.eex
<%= title("User data") %>

    <img src='<%= AdminRoutes.user_path(@conn, :get_photo, @user) %>' />

    <%= if @user.is_enabled do %>
    <h3>User is enabled</h3>
      <% else %>
    <h3>User is disabled</h3>
    <% end %>

    <ul>
      <li>
        <strong>Username:</strong>
        <%= @user.username %>
      </li>

      <li>
          <strong>Authority:</strong>
          <%= get_in(@user, [:authority, :name]) %>
        </li>

      <li>
        <strong>Name:</strong>
        <%= @user.name %>
      </li>

      <li>
        <strong>Permissions:</strong>
        <%= for p <- @user.permissions, do: "#{p.name} " %>
      </li>

      <li>
        <strong>First name:</strong>
        <%= @user.first_name %>
      </li>

      <li>
        <strong>Last name:</strong>
        <%= @user.last_name %>
      </li>

      <li>
        <strong>Email:</strong>
        <%= @user.email %>
      </li>

    </ul>
      <ul>

      <li>
        <strong>AM:</strong>
        <%= @user.am %>
      </li>

      <li>
        <strong>AM PHXCRD:</strong>
        <%= @user.am_phxcrd %>
      </li>

      <li>
        <strong>Dsn:</strong>
        <%= @user.dsn %>
      </li>

      <li>
        <strong>Kind:</strong>
        <%= @user.kind %>
      </li>

      <li>
        <strong>Extra:</strong>
        <%= @user.extra %>
      </li>

      <li>
        <strong>Obj cls:</strong>
        <%= @user.obj_cls %>
      </li>
    </ul>



<span><%= link "Edit", to: AdminRoutes.user_path(@conn, :edit, @user), class: "btn btn-warning" %></span>
<span><%= link "Change password", to: AdminRoutes.user_path(@conn, :change_password_get, @user), class: "btn btn-danger" %></span>
<span><%= link "Back", to: AdminRoutes.user_path(@conn, :index), class: "btn btn-secondary" %></span>